version: '3.6'

# api: 5001
# rabbitmq: 5672, admin: 5673
# mongo: 5017
# redis: 5379

services:
  api:
    environment:
      - NODE_ENV=dev
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 5001:3000
    networks:
      - vitruveo
    restart: always

  rabbitmq:
    image: rabbitmq:3.12.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5673:15672
      - 5672:5672
    restart: always
    networks:
      - vitruveo

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 5017:27017
    networks:
      - vitruveo

  redis:
    image: redis:7.2.3
    restart: always
    command: --requirepass password
    ports:
      - 5379:6379
    networks:
      - vitruveo


networks:
  vitruveo:
    external: true
