FROM node:18

ENV NODE_ENV=production

WORKDIR /app
COPY package*.json /app/

RUN npm pkg delete scripts.prepare && \
  npm ci --omit=dev --no-audit --only=production --verbose

COPY build ./
COPY tools ./tools/
COPY entrypoint.sh ./
COPY static ./static/
COPY public ./public/

ENTRYPOINT [ "/app/entrypoint.sh" ]
CMD [ "wait" ]
