export const MAIL_SENDGRID_TEMPLATE_CONSIGN =
    process.env.MAIL_SENDGRID_TEMPLATE_CONSIGN || '';

export const MAIL_SENDGRID_TEMPLATE_CONSIGN_REJECTED =
    process.env.MAIL_SENDGRID_TEMPLATE_CONSIGN_REJECTED || '';
